FROM maven:3.9-amazoncorretto-8 AS build
WORKDIR /usr/app
COPY . /usr/app
RUN cd /usr/app && mvn clean install -Dskiptests 

FROM openjdk:8-jdk-alpine
# Environment Variable that defines the endpoint of sentiment-analysis python api.
ENV SA_LOGIC_API_URL http://localhost:5000
COPY --from=build /usr/app/targetspring-petclinic-2.7.0-SNAPSHOT.jar /
EXPOSE 8080
CMD ["java", "-jar", "targetspring-petclinic-2.7.0-SNAPSHOT.jar", "--sa.logic.api.url=${SA_LOGIC_API_URL}"]
